
          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800 border-bottom">Agregar Productos</h1>
        
        <form action="" method="post" class="form">
            <input type="hidden" name="add" value="1">

            <div class="form-group"><label for="codigo">Codigo</label><input type="text" name="codigo" id="codigo" class="form-control" placeholder="Codigo"></div>
            <div class="form-group"><label for="nombre">Nombre</label><input type="text" name="nombre" id="nombre" class="form-control" placeholder="Nombre"></div>
            <div class="form-group"><label for="precio">Precio</label><input type="text" name="precio" id="precio" class="form-control" placeholder="Precio"></div>
            <div class="form-group"><label for="descripcion">Descripcion</label><input type="text" name="descripcion" id="descripcion" class="form-control" placeholder="Descripcion"></div>
            <div class="form-group"><label for="existencia">Existencia</label><input type="text" name="existencia" id="existencia" class="form-control" placeholder="Existencia"></div>
            <input type="submit" value="Agregar" class="btn btn-primary">
            
        </form>