          <input type="hidden" value="<?= BASE_URL?>" id="base"> 
          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800 border-bottom">Productos</h1>
          <p class="mb-4 d-flex justify-content-end">
            <a href="<?= BASE_URL ?>productos/add" class="btn btn-secondary btn-icon-split">
              <span class="icon text-white-50">
                <i class="fas fa-file"></i>
              </span>
              <span class="text">Agregar Producto</span>
            </a>
          </p>

          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <?= $this->titulo ?>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered text-center datosProductos" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>CODIGO</th>
                      <th>NOMBRE</th>
                      <th>PRECIO</th>
                      <th>DESCRIPCION</th>
                      <th>EXISTENCIA</th>
                      <th>ACTUALIZAR</th>
                      <th>ELIMINAR</th>
                    </tr>
                  </thead>
                 
                  <tbody>
                    <?= $this->contenido ?>
                  </tbody>
                </table>
              </div>
            </div>
          </div>

           <!-- Logout Modal-->
  <div class="modal fade" id="modalEditar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <form class="form actpro">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Actualizar los productos</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>

          <div class="modal-body">
          
              <input type="hidden" id='id'>
              <div class="form-group"><label for="precio">Precio</label><input type="text" id="precio" class="form-control" placeholder="Precio"></div>
              <div class="form-group"><label for="existencia">Existencia</label><input type="text" id="existencia" class="form-control" placeholder="Existencia"></div>
            
              
          </div>

          <div class="modal-footer">
            <button type="submit" class="btn btn-secondary">Guardar</button>
          </div>
        </form>
      </div>
    </div>
  </div>