<h1 class="h3 mb-2 text-gray-800 border-bottom">Servicio de Recargas Claro</h1><br>
        
        <form action="" method="post" class="form">
            <input type="hidden" name="add" value="1">

            <div class="form-group"><label for="codigo">INGRESAR CODIGO</label><input type="text" name="codigo" id="codigo" class="form-control" placeholder="Ingrese su Codigo Claro"></div>
            <input type="submit" value="Enviar" class="btn btn-primary">
            
        </form><br>


<h1 class="h3 mb-2 text-gray-800 border-bottom">Servicio de Recargas Tigo</h1><br>
        
        <form action="" method="post" class="form">
            <input type="hidden" name="add" value="1">

            <div class="form-group"><label for="codigo">INGRESAR CODIGO</label><input type="text" name="codigo" id="codigo" class="form-control" placeholder="Ingrese su Codigo Tigo"></div>
            <input type="submit" value="Enviar" class="btn btn-primary">
            
        </form>