<div class="row">
    <div class="col-md-9 row filtros">
        <div class="col-md-3 samsung">
            <img src="<?=PLANTILLA?>img/1.png" alt="" class="img-fluid border">
            <p>Samsung A20S </p>
            <a href="#" class="btn btn-info">ver mas</a>
        </div>
        <div class="col-md-3 huawei">
            <img src="<?=PLANTILLA?>img/2.png" alt="" class="img-fluid border">
            <p>HUAWEI P40 PRO</p>
            <a href="#" class="btn btn-info">ver mas</a>
        </div>
        <div class="col-md-3 apple">
            <img src="<?=PLANTILLA?>img/3.png" alt="" class="img-fluid border">
            <p>Iphone x, Iphone 12</p>
            <a href="#" class="btn btn-info">ver mas</a>
        </div>
        <div class="col-md-3 redmi">
            <img src="<?=PLANTILLA?>img/4.png" alt="" class="img-fluid border">
            <p>Redmi Note 8 Pro Azul</p>
            <a href="#" class="btn btn-info">ver mas</a>
        </div>

        <div class="col-md-3 samsung">
            <img src="<?=PLANTILLA?>img/5.png" alt="" class="img-fluid border">
            <p>Samsung A51</p>
            <a href="#" class="btn btn-info">ver mas</a>
        </div>
        <div class="col-md-3 apple">
            <img src="<?=PLANTILLA?>img/6.png" alt="" class="img-fluid border">
            <p>Iphone 8 plus</p>
            <a href="#" class="btn btn-info">ver mas</a>
        </div>
        <div class="col-md-3 huawei">
            <img src="<?=PLANTILLA?>img/7.png" alt="" class="img-fluid border">
            <p>Huawei Y9</p>
            <a href="#" class="btn btn-info">ver mas</a>
        </div>
        <div class="col-md-3 redmi">
            <img src="<?=PLANTILLA?>img/8.png" alt="" class="img-fluid border">
            <p>Redmi Note 9 Pro</p>
            <a href="#" class="btn btn-info">ver mas</a>
        </div>
    </div>

    <div class="col-md-3">
        <p class='text-center font-weight-bold border-bottom'>Categorias</p>
        
        <a href="#" class='btn btn-block btn-warning my-1 categoria' data-filter='*'>Todos</a>
        <a href="#" class='btn btn-block btn-info my-1 categoria' data-filter='.samsung'>Samsung</a>
        <a href="#" class='btn btn-block btn-success my-1 categoria' data-filter='.apple'>Apple</a>
        <a href="#" class='btn btn-block btn-primary my-1 categoria' data-filter='.huawei'>Huawei</a>
        <a href="#" class='btn btn-block btn-danger my-1 categoria' data-filter='.redmi'>Redmi</a>
    </div>
</div>