<form method='POST'>
  <div class="form-group">
    <input type="hidden" name="ingresar" value="1">
    <label for="exampleInputEmail1">Nombre de Usuario</label>
    <input type="text" class="form-control" id="usuario" name="usuario" aria-describedby="emailHelp" placeholder="Escriba Nombre de Usuario">
  </div>

  <div class="form-group">
    <label for="exampleInputPassword1">Contraseña</label>
    <input type="password" class="form-control" id="clave" name="clave"placeholder="Contraseña">
  </div>

  <div class="form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Ingresar</button>
</form>